/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VantagensRouteImport } from './routes/vantagens'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SejaEntregadorRouteImport } from './routes/seja-entregador'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as EntregadoresRouteImport } from './routes/entregadores'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroEntregadorRouteImport } from './routes/cadastro-entregador'
import { Route as CadastrarEstabelecimentoRouteImport } from './routes/cadastrar-estabelecimento'
import { Route as IndexRouteImport } from './routes/index'

const VantagensRoute = VantagensRouteImport.update({
  id: '/vantagens',
  path: '/vantagens',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SejaEntregadorRoute = SejaEntregadorRouteImport.update({
  id: '/seja-entregador',
  path: '/seja-entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresRoute = EntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEntregadorRoute = CadastroEntregadorRouteImport.update({
  id: '/cadastro-entregador',
  path: '/cadastro-entregador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarEstabelecimentoRoute =
  CadastrarEstabelecimentoRouteImport.update({
    id: '/cadastrar-estabelecimento',
    path: '/cadastrar-estabelecimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastrar-estabelecimento': typeof CadastrarEstabelecimentoRoute
  '/cadastro-entregador': typeof CadastroEntregadorRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/seja-entregador': typeof SejaEntregadorRoute
  '/sobre': typeof SobreRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastrar-estabelecimento': typeof CadastrarEstabelecimentoRoute
  '/cadastro-entregador': typeof CadastroEntregadorRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/seja-entregador': typeof SejaEntregadorRoute
  '/sobre': typeof SobreRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastrar-estabelecimento': typeof CadastrarEstabelecimentoRoute
  '/cadastro-entregador': typeof CadastroEntregadorRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/seja-entregador': typeof SejaEntregadorRoute
  '/sobre': typeof SobreRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastrar-estabelecimento'
    | '/cadastro-entregador'
    | '/como-funciona'
    | '/contato'
    | '/entregadores'
    | '/perguntas-frequentes'
    | '/seja-entregador'
    | '/sobre'
    | '/vantagens'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastrar-estabelecimento'
    | '/cadastro-entregador'
    | '/como-funciona'
    | '/contato'
    | '/entregadores'
    | '/perguntas-frequentes'
    | '/seja-entregador'
    | '/sobre'
    | '/vantagens'
  id:
    | '__root__'
    | '/'
    | '/cadastrar-estabelecimento'
    | '/cadastro-entregador'
    | '/como-funciona'
    | '/contato'
    | '/entregadores'
    | '/perguntas-frequentes'
    | '/seja-entregador'
    | '/sobre'
    | '/vantagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastrarEstabelecimentoRoute: typeof CadastrarEstabelecimentoRoute
  CadastroEntregadorRoute: typeof CadastroEntregadorRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EntregadoresRoute: typeof EntregadoresRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  SejaEntregadorRoute: typeof SejaEntregadorRoute
  SobreRoute: typeof SobreRoute
  VantagensRoute: typeof VantagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vantagens': {
      id: '/vantagens'
      path: '/vantagens'
      fullPath: '/vantagens'
      preLoaderRoute: typeof VantagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seja-entregador': {
      id: '/seja-entregador'
      path: '/seja-entregador'
      fullPath: '/seja-entregador'
      preLoaderRoute: typeof SejaEntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores': {
      id: '/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof EntregadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-entregador': {
      id: '/cadastro-entregador'
      path: '/cadastro-entregador'
      fullPath: '/cadastro-entregador'
      preLoaderRoute: typeof CadastroEntregadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar-estabelecimento': {
      id: '/cadastrar-estabelecimento'
      path: '/cadastrar-estabelecimento'
      fullPath: '/cadastrar-estabelecimento'
      preLoaderRoute: typeof CadastrarEstabelecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastrarEstabelecimentoRoute: CadastrarEstabelecimentoRoute,
  CadastroEntregadorRoute: CadastroEntregadorRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EntregadoresRoute: EntregadoresRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  SejaEntregadorRoute: SejaEntregadorRoute,
  SobreRoute: SobreRoute,
  VantagensRoute: VantagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
