/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VantagensRouteImport } from './routes/vantagens'
import { Route as EntregadoresRouteImport } from './routes/entregadores'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'

const VantagensRoute = VantagensRouteImport.update({
  id: '/vantagens',
  path: '/vantagens',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresRoute = EntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/entregadores': typeof EntregadoresRoute
  '/vantagens': typeof VantagensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/entregadores'
    | '/vantagens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-funciona' | '/contato' | '/entregadores' | '/vantagens'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/contato'
    | '/entregadores'
    | '/vantagens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EntregadoresRoute: typeof EntregadoresRoute
  VantagensRoute: typeof VantagensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vantagens': {
      id: '/vantagens'
      path: '/vantagens'
      fullPath: '/vantagens'
      preLoaderRoute: typeof VantagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores': {
      id: '/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof EntregadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EntregadoresRoute: EntregadoresRoute,
  VantagensRoute: VantagensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
